MAINT: Use un-aliased name to re-use constructor.
Before this change, clang complains with:

error: member 'ndarray_view' has the same name as its class

I'm not well versed enough in the C++ scoping rules to know whether
clang is correct here. I am somewhat confused what this line means
though, since there are multiple possible constructors for us to
take. Is this re-exporting all of them?